### ISSUE TITLE
Tooltip type definition doesn't accept a ref prop

### ISSUE THREAD

**Issue by greg-nulogy** [nulogy/design-system#1430]
### Describe the bug

Currently we can't pass a `ref` prop to the Tooltip component. The Tooltip component uses the `forwardRef` helper so should accept a `ref` prop.

### Steps to reproduce

within PM, client_react:

```
import React from "react";
import { Tooltip } from "@nulogy/components";

export default function Component() {
  const someRef = React.useRef(null);

  return (
    <Tooltip ref={someRef}>
      <span>Children</span>
    </Tooltip>
  );
}
```

### Expected behaviour

No Typescript errors.

Actual behaviour:

```
Property ref does not exist on type
IntrinsicAttributes & TooltipProps & { children?: ReactNode; }
```

### Is your team blocked from moving forward by the bug?

No, we've cast the Tooltip component to allow for a `ref` prop

### Who would you like to fix the bug?

- [ ] Myself
- [X] DesignOps

### When do you need this by?

Unknown, doesn't block current work.

**Comment by haideralsh** [comment]
We're unable to reproduce this inside of the NDS repo. We have a story called `WithRef` for the tooltip that compiles using TypeScript v4.9.5 and this [tsconfig](https://github.com/nulogy/design-system/blob/master/tsconfig.json).
